name: Dart CI

on: push

env:
  flutter_channel: 'stable' 
  flutter_version: '1.17.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: subosito/flutter-action@v1
      with:
        channel: ${{ env.flutter_channel }}
        flutter-version: ${{ env.flutter_version }}

    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - run: flutter pub get
      working-directory: healthmonitor_mobile

    - name: Build APK
      run: flutter build apk
      working-directory: healthmonitor_mobile

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: healthmonitor_mobile/build/app/outputs/apk/release/app-release.apk
        
